### ISSUE TITLE
RNN=None causes error at line 171 in snli_rnn.py (Theano)

### ISSUE THREAD

**Issue by bradleypallen** [Smerity/keras_snli#1]
Verified on Mac OSX and Ubuntu. Running Keras 1.0.8 with Theano backend. RNN=recurrent.GRU works fine, but with RNN=None I get the following:

$ python snli_rnn.py
Using Theano backend.
82
62
59
55
57
30
RNN / Embed / Sent = None, 300, 300
GloVe / Trainable Word Embeddings = True, False
Build model...
Vocab size = 42391
Loading GloVe
Total number of null word embeddings:
4043
Traceback (most recent call last):
  File "snli_rnn.py", line 171, in <module>
    prem = BatchNormalization()(prem)
  File "/Users/bradleyallen/anaconda/envs/dlnotebook/lib/python2.7/site-packages/Keras-1.0.8-py2.7.egg/keras/engine/topology.py", line 494, in **call**
    self.assert_input_compatibility(x)
  File "/Users/bradleyallen/anaconda/envs/dlnotebook/lib/python2.7/site-packages/Keras-1.0.8-py2.7.egg/keras/engine/topology.py", line 411, in assert_input_compatibility
    str(K.ndim(x)))
Exception: Input 0 is incompatible with layer batchnormalization_1: expected ndim=3, found ndim=2

**Comment by Smerity** [comment]
Odd. I use the TensorFlow backend for Keras and whilst it shouldn't matter I was able to reproduce your exception using the Theano backend. Given that the actual RNNs (GRU / LSTM) work, this suggests the issues lies with:
`SumEmbeddings = keras.layers.core.Lambda(lambda x: K.sum(x, axis=1))`

Turns out that Theano requires `output_shape` be provided by the Lambda layer whilst TensorFlow can infer it.

I'd also note to try both backends. I may have a buggy setup but the Theano backend is far slower for the summation of word embeddings, which is strange given the relative simplicity.

Thanks for noting the bug! Hugely important if I want to merge this in as a Keras example! :)

**Comment by bradleypallen** [comment]
Confirmed working now on my setup. Will try both backends as you suggest. Thanks so much for the quick turnaround; this example is very useful (to me at least) from a pedagogical point of view and would be great merged into Keras.

**Comment by bradleypallen** [comment]
Just to follow up, FWIW I ran both Sum and GRU on my setup (AWS EC2 g2.2xlarge, Bitfusion Ubuntu 14 Theano AMI, Theano 0.8.2, TensorFlow 0.10.0rc0, Keras 1.0.8) using both backends. Results were:

| Metric | sum(word vectors) using Theano | sum(word vectors) using TensorFlow | GRU using Theano | GRU using TensorFlow |
| --- | --- | --- | --- | --- |
| average secs/epoch | 86 | 47.5 | 547 | 442.5 |
| test accuracy | 0.8313 | 0.8243 | 0.8165 | 0.8118 |

... which is consistent with your observation, with the caveat that, due to an incompatibility between Keras 1.0.8 and the package structure of TensorFlow 0.7.1, I had to use the bleeding edge TensorFlow build (0.10.0rc0) in comparison with the current but older Theano 0.8.2 release.

**Comment by Smerity** [comment]
Thanks for the follow up - and glad it's working for you now! ^_^

I'd be curious where the slowdown comes from. For `sum(word vectors)` I could easily imagine that they way Keras's Lambda is implemented between backends is the difference.

Also, +1 for the 83.1 test accuracy! I got some higher numbers like that for `sum(word vectors)` on a few runs but decided to report 82.4 as that was the consistent average over runs.
